#!/bin/bash
#
# Wrapper script to run the craft Docker image as a container.

set -e  # Exit on any error

readonly IMAGE_NAME="craft-exec:latest"
readonly FOLDER_NAME=$(basename "$(pwd)")

docker run --rm \
  -v "$(pwd):/${FOLDER_NAME}" \
  -u "$(id -u):$(id -g)" \
  -w "/${FOLDER_NAME}" \
  "$IMAGE_NAME" \
  "$@"
