#!/bin/bash

IMAGE_NAME="craft-exec:latest"

FOLDER_NAME=$(basename "$(pwd)")

docker run --rm \
  -v "$(pwd):/${FOLDER_NAME}" \
  -u "$(id -u):$(id -g)" \
  -w "/${FOLDER_NAME}" \
  "$IMAGE_NAME" \
  "$@"
