name: PROJECT_NAME

services:
  java-env:
    container_name: ${COMPOSE_PROJECT_NAME}-java-env
    build:
      context: .
      target: dev
    image: ${COMPOSE_PROJECT_NAME}-java-env:latest
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]
